// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: e2e.proto

package e2e

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Basic just tests basic fields, including oneofs and so on that don't
// generally work automatically with encoding/json.
type Basic struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	A     string                 `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	// Types that are valid to be assigned to B:
	//
	//	*Basic_Int
	//	*Basic_Str
	B             isBasic_B         `protobuf_oneof:"b"`
	Map           map[string]string `protobuf:"bytes,4,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	O             *string           `protobuf:"bytes,5,opt,name=o,proto3,oneof" json:"o,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Basic) Reset() {
	*x = Basic{}
	mi := &file_e2e_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Basic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Basic) ProtoMessage() {}

func (x *Basic) ProtoReflect() protoreflect.Message {
	mi := &file_e2e_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Basic.ProtoReflect.Descriptor instead.
func (*Basic) Descriptor() ([]byte, []int) {
	return file_e2e_proto_rawDescGZIP(), []int{0}
}

func (x *Basic) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *Basic) GetB() isBasic_B {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *Basic) GetInt() int32 {
	if x != nil {
		if x, ok := x.B.(*Basic_Int); ok {
			return x.Int
		}
	}
	return 0
}

func (x *Basic) GetStr() string {
	if x != nil {
		if x, ok := x.B.(*Basic_Str); ok {
			return x.Str
		}
	}
	return ""
}

func (x *Basic) GetMap() map[string]string {
	if x != nil {
		return x.Map
	}
	return nil
}

func (x *Basic) GetO() string {
	if x != nil && x.O != nil {
		return *x.O
	}
	return ""
}

type isBasic_B interface {
	isBasic_B()
}

type Basic_Int struct {
	Int int32 `protobuf:"varint,2,opt,name=int,proto3,oneof"`
}

type Basic_Str struct {
	Str string `protobuf:"bytes,3,opt,name=str,proto3,oneof"`
}

func (*Basic_Int) isBasic_B() {}

func (*Basic_Str) isBasic_B() {}

// Test nested types
type Nested struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nested) Reset() {
	*x = Nested{}
	mi := &file_e2e_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nested) ProtoMessage() {}

func (x *Nested) ProtoReflect() protoreflect.Message {
	mi := &file_e2e_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nested.ProtoReflect.Descriptor instead.
func (*Nested) Descriptor() ([]byte, []int) {
	return file_e2e_proto_rawDescGZIP(), []int{1}
}

type Nested_Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Basic         *Basic                 `protobuf:"bytes,1,opt,name=basic,proto3" json:"basic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nested_Message) Reset() {
	*x = Nested_Message{}
	mi := &file_e2e_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nested_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nested_Message) ProtoMessage() {}

func (x *Nested_Message) ProtoReflect() protoreflect.Message {
	mi := &file_e2e_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nested_Message.ProtoReflect.Descriptor instead.
func (*Nested_Message) Descriptor() ([]byte, []int) {
	return file_e2e_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Nested_Message) GetBasic() *Basic {
	if x != nil {
		return x.Basic
	}
	return nil
}

var File_e2e_proto protoreflect.FileDescriptor

const file_e2e_proto_rawDesc = "" +
	"\n" +
	"\te2e.proto\x12\x03e2e\"\xba\x01\n" +
	"\x05Basic\x12\f\n" +
	"\x01a\x18\x01 \x01(\tR\x01a\x12\x12\n" +
	"\x03int\x18\x02 \x01(\x05H\x00R\x03int\x12\x12\n" +
	"\x03str\x18\x03 \x01(\tH\x00R\x03str\x12%\n" +
	"\x03map\x18\x04 \x03(\v2\x13.e2e.Basic.MapEntryR\x03map\x12\x11\n" +
	"\x01o\x18\x05 \x01(\tH\x01R\x01o\x88\x01\x01\x1a6\n" +
	"\bMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x03\n" +
	"\x01bB\x04\n" +
	"\x02_o\"5\n" +
	"\x06Nested\x1a+\n" +
	"\aMessage\x12 \n" +
	"\x05basic\x18\x01 \x01(\v2\n" +
	".e2e.BasicR\x05basicB\vZ\t./e2e;e2eb\x06proto3"

var (
	file_e2e_proto_rawDescOnce sync.Once
	file_e2e_proto_rawDescData []byte
)

func file_e2e_proto_rawDescGZIP() []byte {
	file_e2e_proto_rawDescOnce.Do(func() {
		file_e2e_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_e2e_proto_rawDesc), len(file_e2e_proto_rawDesc)))
	})
	return file_e2e_proto_rawDescData
}

var file_e2e_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_e2e_proto_goTypes = []any{
	(*Basic)(nil),          // 0: e2e.Basic
	(*Nested)(nil),         // 1: e2e.Nested
	nil,                    // 2: e2e.Basic.MapEntry
	(*Nested_Message)(nil), // 3: e2e.Nested.Message
}
var file_e2e_proto_depIdxs = []int32{
	2, // 0: e2e.Basic.map:type_name -> e2e.Basic.MapEntry
	0, // 1: e2e.Nested.Message.basic:type_name -> e2e.Basic
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_e2e_proto_init() }
func file_e2e_proto_init() {
	if File_e2e_proto != nil {
		return
	}
	file_e2e_proto_msgTypes[0].OneofWrappers = []any{
		(*Basic_Int)(nil),
		(*Basic_Str)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_e2e_proto_rawDesc), len(file_e2e_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_e2e_proto_goTypes,
		DependencyIndexes: file_e2e_proto_depIdxs,
		MessageInfos:      file_e2e_proto_msgTypes,
	}.Build()
	File_e2e_proto = out.File
	file_e2e_proto_goTypes = nil
	file_e2e_proto_depIdxs = nil
}
