// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: e2e_service.proto

package e2e

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_e2e_service_proto protoreflect.FileDescriptor

const file_e2e_service_proto_rawDesc = "" +
	"\n" +
	"\x11e2e_service.proto\x12\x03e2e\x1a\te2e.proto2(\n" +
	"\x03E2E\x12!\n" +
	"\x05Hello\x12\n" +
	".e2e.Basic\x1a\n" +
	".e2e.Basic\"\x00B\vZ\t./e2e;e2eb\x06proto3"

var file_e2e_service_proto_goTypes = []any{
	(*Basic)(nil), // 0: e2e.Basic
}
var file_e2e_service_proto_depIdxs = []int32{
	0, // 0: e2e.E2E.Hello:input_type -> e2e.Basic
	0, // 1: e2e.E2E.Hello:output_type -> e2e.Basic
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_e2e_service_proto_init() }
func file_e2e_service_proto_init() {
	if File_e2e_service_proto != nil {
		return
	}
	file_e2e_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_e2e_service_proto_rawDesc), len(file_e2e_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_e2e_service_proto_goTypes,
		DependencyIndexes: file_e2e_service_proto_depIdxs,
	}.Build()
	File_e2e_service_proto = out.File
	file_e2e_service_proto_goTypes = nil
	file_e2e_service_proto_depIdxs = nil
}
